import type { ExprNode, NamespaceNode, RelationNode, PermissionNode, SubjectTypeNode } from './ast.js';

const HEADER = `// AUTO-GENERATED by pdsl — do not edit.\n`;

const ts = String.raw;

const usedBuilders = (ns: NamespaceNode): Set<string> => {
    const used = new Set<string>(['defineNamespace']);
    const visit = (e: ExprNode): void => {
        switch (e.kind) {
            case 'ref':
                used.add('computed');
                return;
            case 'ttu':
                used.add('tupleToUserset');
                return;
            case 'union':
                used.add('union');
                e.children.forEach(visit);
                return;
            case 'intersection':
                used.add('intersection');
                e.children.forEach(visit);
                return;
            case 'exclusion':
                used.add('exclusion');
                visit(e.base);
                visit(e.subtract);
                return;
        }
    };
    for (const m of ns.members) {
        if (m.kind === 'permission') visit(m.expr);
    }
    return used;
};

const subjectLiteral = (s: SubjectTypeNode): string => {
    if (s.relation !== undefined) return `'${s.namespace}.${s.relation}'`;
    if (s.wildcard) return `'${s.namespace}.*'`;
    return `'${s.namespace}'`;
};

const renderExpr = (e: ExprNode): string => {
    switch (e.kind) {
        case 'ref':
            return `computed('${e.name}')`;
        case 'ttu':
            return `tupleToUserset('${e.tupleRelation}', '${e.computedRelation}')`;
        case 'union':
            return `union(${e.children.map(renderExpr).join(', ')})`;
        case 'intersection':
            return `intersection(${e.children.map(renderExpr).join(', ')})`;
        case 'exclusion':
            return `exclusion(${renderExpr(e.base)}, ${renderExpr(e.subtract)})`;
    }
};

const renderRelation = (r: RelationNode): string => {
    const subjects = r.subjects.map(subjectLiteral).join(', ');
    return `        ${r.name}: { subjects: [${subjects}] },`;
};

const renderPermission = (p: PermissionNode): string => {
    return `        ${p.name}: ${renderExpr(p.expr)},`;
};

/** A rendered namespace file — the namespace name and the TypeScript source string. */
export interface NamespaceFile {
    namespace: string;
    source: string;
}

/** Shared options across {@link renderNamespace} and {@link renderIndex}. */
export interface CodegenOptions {
    /**
     * Import specifier for the runtime `@maroonedsoftware/permissions` package.
     * Override when the generated code lives in a workspace that imports
     * permissions under a different alias (rare).
     */
    permissionsImport?: string;
}

const DEFAULT_PERMISSIONS_IMPORT = '@maroonedsoftware/permissions';

/**
 * Render one {@link NamespaceNode} into a TypeScript module. Imports only the
 * builders actually used in the namespace's permission expressions
 * (`defineNamespace` is always included). The output is unformatted —
 * `compile()` runs prettier over it when `config.prettier` is set.
 */
export const renderNamespace = (ns: NamespaceNode, opts: CodegenOptions = {}): NamespaceFile => {
    const importFrom = opts.permissionsImport ?? DEFAULT_PERMISSIONS_IMPORT;
    const builders = [...usedBuilders(ns)].sort();
    const relations = ns.members.filter((m): m is RelationNode => m.kind === 'relation');
    const permissions = ns.members.filter((m): m is PermissionNode => m.kind === 'permission');

    const relationsBlock = relations.length === 0 ? '    relations: {},' : `    relations: {\n${relations.map(renderRelation).join('\n')}\n    },`;
    const permissionsBlock =
        permissions.length === 0 ? '    permissions: {},' : `    permissions: {\n${permissions.map(renderPermission).join('\n')}\n    },`;

    const source =
        HEADER +
        ts`import { ${builders.join(', ')} } from '${importFrom}';

export const ${ns.name} = defineNamespace('${ns.name}', {
${relationsBlock}
${permissionsBlock}
});
`;

    return { namespace: ns.name, source };
};

/** Options for {@link renderIndex} — the per-namespace import map plus the shared codegen options. */
export interface IndexOptions {
    permissionsImport?: string;
    namespaceImports: { name: string; from: string }[];
}

/**
 * Render the aggregate model module: imports each per-namespace file, re-exports
 * the namespaces, and constructs a single `AuthorizationModel`. Namespaces are
 * sorted alphabetically for deterministic output.
 */
export const renderIndex = (opts: IndexOptions): string => {
    const importFrom = opts.permissionsImport ?? DEFAULT_PERMISSIONS_IMPORT;
    const sorted = [...opts.namespaceImports].sort((a, b) => a.name.localeCompare(b.name));
    const imports = sorted.map(i => `import { ${i.name} } from '${i.from}';`).join('\n');
    const reexports = sorted.map(i => `export { ${i.name} };`).join('\n');
    const list = sorted.map(i => `    ${i.name},`).join('\n');
    return (
        HEADER +
        ts`import { AuthorizationModel } from '${importFrom}';
${imports}

${reexports}

export const model = new AuthorizationModel([
${list}
]);
`
    );
};
