import { describe, expect, it } from 'vitest';
import { renderIndex, renderNamespace } from '../src/codegen.js';
import { parse } from '../src/parser.js';

const ns = (source: string) => parse({ source, filename: 'inline.perm' }).namespaces[0]!;

describe('codegen', () => {
    it('emits a header so generated files are obviously generated', () => {
        const file = renderNamespace(ns(`namespace doc { relation x: user }`));
        expect(file.source).toContain('// AUTO-GENERATED by pdsl');
    });

    it('only imports builders that are actually used', () => {
        const onlyUnion = renderNamespace(
            ns(`namespace doc {
  relation a: user
  relation b: user
  permission p = a | b
}`),
        );
        expect(onlyUnion.source).toContain('union');
        expect(onlyUnion.source).toContain('computed');
        expect(onlyUnion.source).not.toContain('intersection');
        expect(onlyUnion.source).not.toContain('exclusion');
        expect(onlyUnion.source).not.toContain('tupleToUserset');
    });

    it('renders subject types correctly', () => {
        const file = renderNamespace(
            ns(`namespace doc {
  relation a: user
  relation b: user, user:*, org#admin
}`),
        );
        expect(file.source).toContain(`a: { subjects: ['user'] }`);
        expect(file.source).toContain(`b: { subjects: ['user', 'user:*', 'org#admin'] }`);
    });

    it('renders all expression operators', () => {
        const file = renderNamespace(
            ns(`namespace doc {
  relation a: user
  relation b: user
  relation c: user
  relation parent: doc
  permission p1 = a | b
  permission p2 = a & b
  permission p3 = a - b
  permission p4 = parent->a
  permission p5 = (a | b) & c - parent->a
}`),
        );
        expect(file.source).toContain(`p1: union(computed('a'), computed('b'))`);
        expect(file.source).toContain(`p2: intersection(computed('a'), computed('b'))`);
        expect(file.source).toContain(`p3: exclusion(computed('a'), computed('b'))`);
        expect(file.source).toContain(`p4: tupleToUserset('parent', 'a')`);
        expect(file.source).toContain(
            `p5: exclusion(intersection(union(computed('a'), computed('b')), computed('c')), tupleToUserset('parent', 'a'))`,
        );
    });

    it('emits empty relations / permissions blocks correctly', () => {
        const empty = renderNamespace(ns(`namespace doc {}`));
        expect(empty.source).toContain('relations: {}');
        expect(empty.source).toContain('permissions: {}');
    });

    it('uses the configured permissions import specifier', () => {
        const file = renderNamespace(ns(`namespace doc { relation x: user }`), {
            permissionsImport: '#permissions',
        });
        expect(file.source).toContain(`from '#permissions'`);
    });

    it('renders the aggregate index with sorted imports + AuthorizationModel', () => {
        const idx = renderIndex({
            namespaceImports: [
                { name: 'doc', from: './doc.js' },
                { name: 'folder', from: './folder.js' },
                { name: 'user', from: './user.js' },
            ],
        });
        expect(idx).toContain(`import { AuthorizationModel } from '@maroonedsoftware/permissions';`);
        expect(idx).toContain(`import { doc } from './doc.js';`);
        expect(idx).toContain(`import { folder } from './folder.js';`);
        expect(idx).toContain(`import { user } from './user.js';`);
        expect(idx).toContain(`export const model = new AuthorizationModel(`);
        // Sorted alphabetically
        const docIdx = idx.indexOf('doc');
        const folderIdx = idx.indexOf('folder');
        const userIdx = idx.indexOf('user');
        expect(docIdx).toBeLessThan(folderIdx);
        expect(folderIdx).toBeLessThan(userIdx);
    });
});
